# Generated by Django 5.2.14 on 2026-05-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, max_length=80)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sequência numérica',
                'verbose_name_plural': 'Sequências numéricas',
                'ordering': ['scope', 'year'],
                'constraints': [models.UniqueConstraint(fields=('scope', 'year'), name='unique_number_sequence_scope_year')],
            },
        ),
    ]
