# Generated by Django 5.2.14 on 2026-05-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_numbersequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Alteração'), ('delete', 'Exclusão'), ('status_change', 'Alteração de status'), ('financial_create', 'Criação financeira'), ('financial_update', 'Alteração financeira'), ('financial_payment', 'Pagamento/recebimento'), ('financial_reversal', 'Estorno financeiro'), ('financial_discount', 'Alteração de desconto'), ('financial_status', 'Status financeiro'), ('critical_update', 'Alteração crítica'), ('login', 'Login'), ('logout', 'Logout'), ('permission', 'Permissão'), ('system', 'Sistema')], db_index=True, max_length=30),
        ),
    ]
