# Generated by Django 5.2.14 on 2026-05-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_ai_prompts_and_token_limit"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiprompt",
            new_name="ai_assistan_task_cc6005_idx",
            old_name="ai_assista_task_6af6d4_idx",
        ),
    ]
