# Generated by Django 5.2.14 on 2026-05-10 07:27

import accounts.fields
from django.db import migrations


def encrypt_existing_api_keys(apps, schema_editor):
    AIProviderConfiguration = apps.get_model('ai_assistant', 'AIProviderConfiguration')
    for config in AIProviderConfiguration.objects.exclude(api_key=''):
        config.api_key = config.api_key
        config.save(update_fields=['api_key'])


def decrypt_existing_api_keys(apps, schema_editor):  # noqa: ARG001
    from accounts.encryption import decrypt_credential

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, api_key FROM ai_assistant_aiproviderconfiguration WHERE api_key <> ''")
        rows = cursor.fetchall()
        for pk, raw_api_key in rows:
            cursor.execute(
                "UPDATE ai_assistant_aiproviderconfiguration SET api_key = %s WHERE id = %s",
                [decrypt_credential(raw_api_key), pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_rename_ai_assista_task_6af6d4_idx_ai_assistan_task_cc6005_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfiguration',
            name='api_key',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(encrypt_existing_api_keys, decrypt_existing_api_keys),
    ]
