# Generated by ChatGPT on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(model_name="supplier", name="person_type", field=models.CharField(choices=[("individual", "Pessoa física"), ("company", "Pessoa jurídica")], db_index=True, default="company", max_length=20)),
        migrations.AddField(model_name="supplier", name="last_name", field=models.CharField(blank=True, max_length=120, verbose_name="Sobrenome")),
        migrations.AddField(model_name="supplier", name="trade_name", field=models.CharField(blank=True, max_length=160, verbose_name="Nome fantasia")),
        migrations.AddField(model_name="supplier", name="state_registration", field=models.CharField(blank=True, max_length=40, verbose_name="Inscrição estadual")),
        migrations.AddField(model_name="supplier", name="municipal_registration", field=models.CharField(blank=True, max_length=40, verbose_name="Inscrição municipal")),
        migrations.AddField(model_name="supplier", name="birth_date", field=models.DateField(blank=True, null=True, verbose_name="Data de nascimento/fundação")),
        migrations.AddField(model_name="supplier", name="secondary_phone", field=models.CharField(blank=True, max_length=40, verbose_name="Telefone secundário")),
        migrations.AddField(model_name="supplier", name="zip_code", field=models.CharField(blank=True, max_length=9, verbose_name="CEP")),
        migrations.AddField(model_name="supplier", name="address_line", field=models.CharField(blank=True, max_length=180, verbose_name="Endereço")),
        migrations.AddField(model_name="supplier", name="address_number", field=models.CharField(blank=True, max_length=20, verbose_name="Número")),
        migrations.AddField(model_name="supplier", name="address_complement", field=models.CharField(blank=True, max_length=120, verbose_name="Complemento")),
        migrations.AddField(model_name="supplier", name="district", field=models.CharField(blank=True, max_length=120, verbose_name="Bairro")),
        migrations.AddField(model_name="supplier", name="city", field=models.CharField(blank=True, max_length=120, verbose_name="Cidade")),
        migrations.AddField(model_name="supplier", name="state", field=models.CharField(blank=True, max_length=2, verbose_name="UF")),
        migrations.AddField(model_name="supplier", name="country", field=models.CharField(blank=True, default="Brasil", max_length=80, verbose_name="País")),
        migrations.AddField(model_name="supplier", name="custom_data", field=models.JSONField(blank=True, default=dict)),
        migrations.AlterField(model_name="supplier", name="name", field=models.CharField(max_length=160, verbose_name="Nome / Razão social")),
        migrations.AlterField(model_name="supplier", name="document", field=models.CharField(blank=True, db_index=True, max_length=18, verbose_name="CPF/CNPJ")),
        migrations.AlterField(model_name="supplier", name="phone", field=models.CharField(blank=True, max_length=40, verbose_name="WhatsApp / telefone principal")),
        migrations.AlterField(model_name="supplier", name="contact_person", field=models.CharField(blank=True, max_length=120, verbose_name="Pessoa de contato")),
        migrations.AlterField(model_name="supplier", name="address", field=models.TextField(blank=True, verbose_name="Endereço legado")),
        migrations.AlterField(model_name="supplier", name="notes", field=models.TextField(blank=True, verbose_name="Observações")),
        migrations.AlterModelOptions(name="supplier", options={"ordering": ["name", "last_name"]}),
    ]
