import React from "react";
import { Badge } from "../ui/TailwindPrimitives.jsx";

const variants = {
  pending: "secondary",
  partial: "warning",
  paid: "success",
  sending: "info",
  sent: "warning",
  failed: "danger",
  skipped: "warning",
  email: "primary",
  whatsapp: "success",
  draft: "secondary",
  open: "primary",
  diagnosis: "info",
  awaiting_approval: "warning",
  waiting_parts: "warning",
  approved: "success",
  partially_approved: "success",
  in_progress: "info",
  paused: "warning",
  completed: "success",
  delivered: "primary",
  rejected: "danger",
  expired: "warning",
  converted: "primary",
  cancelled: "danger",
  low: "secondary",
  normal: "primary",
  high: "warning",
  urgent: "danger",
  manual: "primary",
  status_auto: "success",
};

const labels = {
  pending: "Pendente",
  partial: "Parcial",
  paid: "Pago",
  sending: "Enviando",
  sent: "Enviado",
  failed: "Falhou",
  skipped: "Ignorado",
  email: "Email",
  whatsapp: "WhatsApp",
  draft: "Rascunho",
  open: "Aberta",
  diagnosis: "Diagnóstico",
  awaiting_approval: "Aguardando aprovação",
  waiting_parts: "Aguardando peças",
  approved: "Aprovada",
  partially_approved: "Aprovado parcialmente",
  in_progress: "Em execução",
  paused: "Pausada",
  completed: "Concluída",
  delivered: "Entregue",
  rejected: "Recusada",
  expired: "Expirado",
  converted: "Convertido",
  cancelled: "Cancelada",
  low: "Baixa",
  normal: "Normal",
  high: "Alta",
  urgent: "Urgente",
  manual: "Manual",
  status_auto: "Automático",
};

export default function StatusBadge({ value, label, className = "" }) {
  return <Badge bg={variants[value] || "secondary"} className={className}>{label || labels[value] || value || "-"}</Badge>;
}
