# Generated by Django 5.2.14 on 2026-05-07 16:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def recalculate_existing_work_orders(apps, schema_editor):
    WorkOrder = apps.get_model('workshop', 'WorkOrder')
    WorkOrderService = apps.get_model('workshop', 'WorkOrderService')
    WorkOrderPart = apps.get_model('workshop', 'WorkOrderPart')
    WorkOrderPayment = apps.get_model('workshop', 'WorkOrderPayment')
    zero = Decimal('0.00')

    for work_order in WorkOrder.objects.all().iterator():
        services_subtotal = zero
        service_discounts = zero
        for line in WorkOrderService.objects.filter(work_order_id=work_order.id):
            services_subtotal += (line.quantity or zero) * (line.unit_price or zero)
            service_discounts += line.discount_amount or zero

        parts_subtotal = zero
        part_discounts = zero
        for line in WorkOrderPart.objects.filter(work_order_id=work_order.id):
            parts_subtotal += (line.quantity or zero) * (line.unit_price or zero)
            part_discounts += line.discount_amount or zero

        paid_total = sum((payment.amount or zero for payment in WorkOrderPayment.objects.filter(work_order_id=work_order.id)), zero)
        total_discount = service_discounts + part_discounts + (work_order.manual_discount_amount or zero)
        grand_total = services_subtotal + parts_subtotal - total_discount
        work_order.subtotal_services = services_subtotal
        work_order.subtotal_parts = parts_subtotal
        work_order.discount_total = total_discount
        work_order.grand_total = grand_total if grand_total > zero else zero
        work_order.paid_total = paid_total
        work_order.balance_due = work_order.grand_total - paid_total
        work_order.save(update_fields=['subtotal_services', 'subtotal_parts', 'discount_total', 'grand_total', 'paid_total', 'balance_due'])


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_workorder_type_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='manual_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='workorderservice',
            name='source_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_service_lines', to='workshop.servicepackage'),
        ),
        migrations.CreateModel(
            name='ServicePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=220)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('position', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_items', to='workshop.workshopservice')),
                ('service_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.servicepackage')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RunPython(recalculate_existing_work_orders, migrations.RunPython.noop),
    ]
