# Generated by Django 5.2.14 on 2026-05-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_partbrand_default_categories_and_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fipe_brand_code',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fipe_model_code',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fipe_year_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
