# Generated by ChatGPT for cadastro singleton da oficina.

import django.core.validators
from django.db import migrations, models


def create_default_workshop_profile(apps, schema_editor):
    WorkshopProfile = apps.get_model("workshop", "WorkshopProfile")
    WorkshopProfile.objects.get_or_create(
        pk=1,
        defaults={
            "legal_name": "Minha Oficina",
            "trade_name": "Oficina Admin",
            "country": "Brasil",
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0009_vehicle_fipe_brand_code_vehicle_fipe_model_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=180, verbose_name="Razão social")),
                ("trade_name", models.CharField(blank=True, max_length=180, verbose_name="Nome fantasia")),
                ("document_number", models.CharField(blank=True, db_index=True, max_length=18, verbose_name="CNPJ/CPF")),
                ("state_registration", models.CharField(blank=True, max_length=40, verbose_name="Inscrição estadual")),
                ("municipal_registration", models.CharField(blank=True, max_length=40, verbose_name="Inscrição municipal")),
                ("logo", models.FileField(blank=True, upload_to="workshop/logos/", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"])], verbose_name="Logomarca")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_e164", models.CharField(blank=True, max_length=20, verbose_name="Telefone principal / WhatsApp")),
                ("secondary_phone_e164", models.CharField(blank=True, max_length=20, verbose_name="Telefone secundário")),
                ("website", models.URLField(blank=True)),
                ("zip_code", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                ("address_line", models.CharField(blank=True, max_length=180, verbose_name="Endereço")),
                ("address_number", models.CharField(blank=True, max_length=20, verbose_name="Número")),
                ("address_complement", models.CharField(blank=True, max_length=120, verbose_name="Complemento")),
                ("district", models.CharField(blank=True, max_length=120, verbose_name="Bairro")),
                ("city", models.CharField(blank=True, max_length=120, verbose_name="Cidade")),
                ("state", models.CharField(blank=True, max_length=2, verbose_name="UF")),
                ("country", models.CharField(blank=True, default="Brasil", max_length=80, verbose_name="País")),
                ("responsible_name", models.CharField(blank=True, max_length=120, verbose_name="Responsável técnico/administrativo")),
                ("print_header_text", models.CharField(blank=True, max_length=220, verbose_name="Texto do cabeçalho de impressão")),
                ("print_footer_text", models.TextField(blank=True, verbose_name="Rodapé padrão de impressão")),
                ("estimate_terms", models.TextField(blank=True, verbose_name="Condições padrão para orçamentos")),
                ("work_order_terms", models.TextField(blank=True, verbose_name="Condições padrão para ordens de serviço")),
                ("purchase_order_terms", models.TextField(blank=True, verbose_name="Condições padrão para pedidos de compra")),
                ("bank_info", models.TextField(blank=True, verbose_name="Dados bancários para impressão")),
                ("pix_key", models.CharField(blank=True, max_length=120, verbose_name="Chave Pix")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "cadastro da oficina",
                "verbose_name_plural": "cadastro da oficina",
            },
        ),
        migrations.RunPython(create_default_workshop_profile, migrations.RunPython.noop),
    ]
