# Generated by ChatGPT on 2026-05-08

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workshop", "0014_featured_catalog_items_and_unit_normalization"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderCustomerApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_type", models.CharField(choices=[("estimate", "Orçamento"), ("work_order", "Ordem de serviço"), ("receipt", "Recibo")], db_index=True, default="estimate", max_length=20)),
                ("token", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("approved", "Aprovado"), ("rejected", "Recusado"), ("expired", "Expirado")], db_index=True, default="pending", max_length=20)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("customer_name_snapshot", models.CharField(blank=True, max_length=180)),
                ("customer_email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("customer_phone_snapshot", models.CharField(blank=True, max_length=30)),
                ("decision_name", models.CharField(blank=True, max_length=180)),
                ("decision_document", models.CharField(blank=True, max_length=30)),
                ("decision_notes", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("decision_user_agent", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_work_order_approvals", to=settings.AUTH_USER_MODEL)),
                ("work_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_approvals", to="workshop.workorder")),
            ],
            options={
                "verbose_name": "aprovação digital de OS",
                "verbose_name_plural": "aprovações digitais de OS",
                "ordering": ["-requested_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="workordercustomerapproval",
            index=models.Index(fields=["work_order", "status"], name="wo_approval_status_idx"),
        ),
        migrations.AddIndex(
            model_name="workordercustomerapproval",
            index=models.Index(fields=["token", "status"], name="wo_approval_token_idx"),
        ),
    ]
