# Generated by Django 5.2.14 on 2026-05-08 18:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import workshop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_workordercustomerapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopprofile',
            name='delivery_signature_enabled',
            field=models.BooleanField(default=True, verbose_name='Usar assinatura digital na entrega'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='landing_cta_label',
            field=models.CharField(blank=True, default='Solicitar atendimento', max_length=80, verbose_name='Texto do botão principal'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='landing_enabled',
            field=models.BooleanField(default=True, verbose_name='Landing page pública habilitada'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='landing_headline',
            field=models.CharField(blank=True, max_length=180, verbose_name='Título da landing page'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='landing_highlight_text',
            field=models.CharField(blank=True, max_length=180, verbose_name='Destaque curto da landing page'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='landing_subheadline',
            field=models.TextField(blank=True, verbose_name='Subtítulo da landing page'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='technical_checklist_enabled',
            field=models.BooleanField(default=False, verbose_name='Usar checklist técnico nas OS'),
        ),
        migrations.AlterField(
            model_name='workorderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Criada'), ('updated', 'Atualizada'), ('status_changed', 'Status alterado'), ('message_sent', 'Mensagem enviada'), ('payment_added', 'Pagamento registrado'), ('inventory_consumed', 'Estoque consumido'), ('photo_added', 'Foto adicionada'), ('service_started', 'Servico iniciado'), ('service_finished', 'Servico concluido'), ('service_quality_checked', 'Servico conferido'), ('checklist_updated', 'Checklist atualizado'), ('delivery_signed', 'Entrega assinada'), ('note', 'Nota'), ('error', 'Erro')], max_length=40),
        ),
        migrations.CreateModel(
            name='WorkOrderDeliverySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=180)),
                ('recipient_document', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('signature_image', models.FileField(upload_to=workshop.models.work_order_signature_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagem da assinatura')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.TextField(blank=True)),
                ('signed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_work_order_deliveries', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_signature', to='workshop.workorder')),
            ],
            options={
                'verbose_name': 'assinatura de entrega da OS',
                'verbose_name_plural': 'assinaturas de entrega da OS',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopServiceChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=220)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_note', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='workshop.workshopservice')),
            ],
            options={
                'verbose_name': 'item de checklist padrão',
                'verbose_name_plural': 'itens de checklist padrão',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderServiceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=220)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_note', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to=workshop.models.work_order_checklist_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto do checklist')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_work_order_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_checklist_items', to='workshop.workorder')),
                ('work_order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='workshop.workorderservice')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='workshop.workshopservicechecklisttemplate')),
            ],
            options={
                'verbose_name': 'item de checklist da OS',
                'verbose_name_plural': 'itens de checklist da OS',
                'ordering': ['work_order_service_id', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['work_order', 'is_completed'], name='wo_chk_completed_idx'), models.Index(fields=['work_order_service', 'sort_order'], name='wo_chk_service_order_idx')],
            },
        ),
    ]
