# Generated by Django 5.2.14 on 2026-05-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0018_workorder_waiting_parts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordernotificationrule',
            name='trigger_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('diagnosis', 'Diagnostico'), ('awaiting_approval', 'Aguardando aprovacao'), ('waiting_parts', 'Aguardando peca'), ('approved', 'Aprovada'), ('in_progress', 'Em execucao'), ('quality_check', 'Conferencia'), ('ready', 'Pronta para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], max_length=30),
        ),
    ]
