# Generated by ChatGPT for OS approval/rejection and notification recipient targets.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0018_workorder_waiting_parts_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("open", "Aberta"),
                    ("diagnosis", "Diagnostico"),
                    ("awaiting_approval", "Aguardando aprovacao"),
                    ("waiting_parts", "Aguardando peca"),
                    ("approved", "Aprovada"),
                    ("in_progress", "Em execucao"),
                    ("quality_check", "Conferencia"),
                    ("ready", "Pronta para entrega"),
                    ("delivered", "Entregue"),
                    ("rejected", "Recusada"),
                    ("cancelled", "Cancelada"),
                ],
                db_index=True,
                default="open",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workordernotificationrule",
            name="trigger_status",
            field=models.CharField(
                choices=[
                    ("draft", "Rascunho"),
                    ("open", "Aberta"),
                    ("diagnosis", "Diagnostico"),
                    ("awaiting_approval", "Aguardando aprovacao"),
                    ("waiting_parts", "Aguardando peca"),
                    ("approved", "Aprovada"),
                    ("in_progress", "Em execucao"),
                    ("quality_check", "Conferencia"),
                    ("ready", "Pronta para entrega"),
                    ("delivered", "Entregue"),
                    ("rejected", "Recusada"),
                    ("cancelled", "Cancelada"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="workordernotificationrule",
            name="recipient_target",
            field=models.CharField(
                choices=[("customer", "Cliente"), ("workshop", "Oficina"), ("both", "Cliente e oficina")],
                default="customer",
                max_length=20,
                verbose_name="Enviar para",
            ),
        ),
        migrations.AddField(
            model_name="workordermessage",
            name="recipient_target",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
