# Generated by Django 5.2.14 on 2026-05-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0019_alter_workordernotificationrule_trigger_status'),
        ('workshop', '0019_rejected_status_notification_recipients'),
    ]

    operations = [
    ]
