# Generated by Django 5.2.14 on 2026-05-10 16:43

import django.db.models.deletion
from django.db import migrations, models


def map_legacy_work_order_statuses(apps, schema_editor):
    WorkOrder = apps.get_model("workshop", "WorkOrder")
    WorkOrderNotificationRule = apps.get_model("workshop", "WorkOrderNotificationRule")

    status_map = {
        "draft": "open",
        "diagnosis": "open",
        "awaiting_approval": "open",
        "approved": "open",
        "in_progress": "in_progress",
        "waiting_parts": "waiting_parts",
        "quality_check": "completed",
        "ready": "completed",
        "delivered": "completed",
        "rejected": "completed",
        "cancelled": "completed",
    }

    for old_status, new_status in status_map.items():
        WorkOrder.objects.filter(status=old_status).update(status=new_status)
        WorkOrderNotificationRule.objects.filter(trigger_status=old_status).update(trigger_status=new_status)


def reverse_legacy_work_order_statuses(apps, schema_editor):
    # A migracao de volta nao consegue reconstruir os estados historicos antigos com seguranca.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0022_workorderpayment_reversal_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='source_estimate_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_estimate_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='linked_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_parts', to='workshop.workorderservice'),
        ),
        migrations.RunPython(map_legacy_work_order_statuses, reverse_legacy_work_order_statuses),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em execucao'), ('waiting_parts', 'Aguardando pecas'), ('completed', 'Concluida')], db_index=True, default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='workordernotificationrule',
            name='trigger_status',
            field=models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em execucao'), ('waiting_parts', 'Aguardando pecas'), ('completed', 'Concluida')], max_length=30),
        ),
    ]
