# Generated by Django 5.2.14 on 2026-05-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_estimatepartitem_approved_by_customer_and_more'),
        ('workshop', '0023_workorder_source_estimate_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workordernotificationrule',
            options={'ordering': ['entity_type', 'trigger_status', 'channel', 'name']},
        ),
        migrations.AddField(
            model_name='workordermessage',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='attendance.estimate'),
        ),
        migrations.AddField(
            model_name='workordernotificationrule',
            name='entity_type',
            field=models.CharField(choices=[('work_order', 'Ordem de serviço'), ('estimate', 'Orçamento')], db_index=True, default='work_order', max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='workordermessage',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workshop.workorder'),
        ),
        migrations.AlterField(
            model_name='workordernotificationrule',
            name='trigger_status',
            field=models.CharField(max_length=30, verbose_name='Status gatilho'),
        ),
    ]
