# Generated by Django 5.2.14 on 2026-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0024_alter_workordernotificationrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='door_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='steering_type',
            field=models.CharField(blank=True, choices=[('manual', 'Mecânica'), ('hydraulic', 'Hidráulica'), ('electric', 'Elétrica'), ('electro_hydraulic', 'Eletro-hidráulica')], max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automático'), ('automated', 'Automatizado'), ('cvt', 'CVT'), ('dual_clutch', 'Dupla embreagem')], max_length=30),
        ),
    ]
