# Generated by Django 5.2.14 on 2026-05-10 22:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0025_vehicle_door_count_vehicle_has_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='stock_reservation_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_work_order_part_lines', to='workshop.partstockmovement'),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='stock_reservation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='stock_reservation_status',
            field=models.CharField(choices=[('not_applicable', 'Não aplicável'), ('pending', 'Pendente'), ('reserved', 'Reservada'), ('partial', 'Parcial'), ('unavailable', 'Sem estoque')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='stock_reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='stock_reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='stock_shortage_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='partstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Entrada/compra'), ('adjustment', 'Ajuste'), ('reservation', 'Reserva para OS'), ('reservation_release', 'Liberação de reserva'), ('consumption', 'Consumo em OS'), ('reversal', 'Estorno')], max_length=30),
        ),
    ]
