# Generated by Django 5.2.14 on 2026-05-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0027_alter_workorderevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Criada'), ('updated', 'Atualizada'), ('status_changed', 'Status alterado'), ('message_sent', 'Mensagem enviada'), ('payment_added', 'Pagamento registrado'), ('inventory_reserved', 'Estoque reservado'), ('inventory_reservation_released', 'Reserva liberada'), ('inventory_consumed', 'Estoque consumido'), ('purchase_needed', 'Necessidade de compra'), ('photo_added', 'Foto adicionada'), ('service_started', 'Servico iniciado'), ('service_finished', 'Servico concluido'), ('service_quality_checked', 'Servico conferido'), ('checklist_updated', 'Checklist atualizado'), ('delivery_signed', 'Entrega assinada'), ('note', 'Nota'), ('error', 'Erro')], max_length=40),
        ),
    ]
