# Generated by ChatGPT for configurable mobile bottom navigation.

from django.db import migrations, models


def seed_bottom_navigation(apps, schema_editor):
    BottomNavigationItem = apps.get_model("workshop", "BottomNavigationItem")
    defaults = [
        {"position": 10, "label": "Início", "path": "/dashboard/atendimento", "icon": "home", "permission_code": "dashboard.attendance", "highlight": False},
        {"position": 20, "label": "OS", "path": "/work-orders", "icon": "receipt", "permission_code": "work_orders.view", "highlight": False},
        {"position": 30, "label": "Kanban", "path": "/work-orders/kanban", "icon": "clipboard", "permission_code": "work_orders.view", "highlight": False},
        {"position": 40, "label": "Nova OS", "path": "/work-orders/new", "icon": "plus", "permission_code": "work_orders.create", "highlight": True},
        {"position": 50, "label": "Estoque", "path": "/parts", "icon": "box", "permission_code": "parts.manage", "highlight": False},
        {"position": 60, "label": "Financeiro", "path": "/finance/dashboard", "icon": "finance", "permission_code": "finance.view", "highlight": False},
    ]
    for item in defaults:
        BottomNavigationItem.objects.get_or_create(path=item["path"], defaults=item)


def unseed_bottom_navigation(apps, schema_editor):
    BottomNavigationItem = apps.get_model("workshop", "BottomNavigationItem")
    BottomNavigationItem.objects.filter(path__in=[
        "/dashboard/atendimento",
        "/work-orders",
        "/work-orders/kanban",
        "/work-orders/new",
        "/parts",
        "/finance/dashboard",
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0031_workorder_cancellation_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="BottomNavigationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=32, verbose_name="Rótulo")),
                ("path", models.CharField(max_length=180, verbose_name="Rota do frontend")),
                ("icon", models.CharField(choices=[("attendance", "Atendimento"), ("wrench", "Chave / Oficina"), ("receipt", "Ordem / Recibo"), ("clipboard", "Checklist"), ("car", "Veículo"), ("box", "Estoque"), ("cart", "Venda"), ("finance", "Financeiro"), ("chart", "Relatórios"), ("message", "Mensagens"), ("users", "Clientes / Usuários"), ("tools", "Ferramentas"), ("package", "Pacote"), ("gear", "Configurações"), ("send", "Enviar"), ("bell", "Notificações"), ("health", "Saúde do sistema"), ("audit", "Auditoria"), ("home", "Início"), ("plus", "Adicionar")], default="receipt", max_length=30, verbose_name="Ícone")),
                ("permission_code", models.CharField(blank=True, help_text="Opcional. Use uma permissão do sistema, como work_orders.view. Para alternativas, separe por vírgula.", max_length=160, verbose_name="Permissão necessária")),
                ("position", models.PositiveSmallIntegerField(db_index=True, default=10, verbose_name="Ordem")),
                ("highlight", models.BooleanField(default=False, verbose_name="Destacar botão")),
                ("open_in_new_tab", models.BooleanField(default=False, verbose_name="Abrir em nova aba")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "botão do menu inferior",
                "verbose_name_plural": "menu inferior do app",
                "ordering": ["position", "label"],
            },
        ),
        migrations.RunPython(seed_bottom_navigation, unseed_bottom_navigation),
    ]
