# Generated by Django 5.2.14 on 2026-05-14 19:52

from django.db import migrations, models


def forwards_sync_financial_status(apps, schema_editor):
    WorkOrder = apps.get_model("workshop", "WorkOrder")
    for order in WorkOrder.objects.all().only("id", "status", "grand_total", "paid_total"):
        grand_total = order.grand_total or 0
        paid_total = order.paid_total or 0
        if order.status == "cancelled" and paid_total <= 0:
            status = "cancelled"
        elif grand_total > 0 and paid_total >= grand_total:
            status = "paid"
        elif paid_total > 0:
            status = "partial"
        else:
            status = "pending"
        WorkOrder.objects.filter(pk=order.pk).update(financial_status=status)



class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0032_bottomnavigationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='financial_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcial'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='delivery_with_pending_payment_allowed',
            field=models.BooleanField(default=False, verbose_name='Permitir entrega de veículo com pagamento pendente'),
        ),
        migrations.RunPython(forwards_sync_financial_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em execução'), ('waiting_parts', 'Aguardando peças'), ('awaiting_approval', 'Aguardando aprovação'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], db_index=True, default='open', max_length=30),
        ),
    ]
