
"""Serializers do app workshop organizados por dominio.

Este modulo funciona como fachada de compatibilidade para manter imports antigos,
por exemplo: ``from workshop.serializers import WorkOrderSerializer``.
"""

from .profile import WorkshopProfileSerializer, PublicLandingSerializer
from .catalog import (
    WorkshopServiceChecklistTemplateSerializer,
    ServiceDefaultPartSerializer,
    GeneralCategorySerializer,
    PartBrandSerializer,
    WorkshopServiceSerializer,
    ServicePackageItemSerializer,
    ServicePackageSerializer,
    PartSerializer,
    PartStockMovementSerializer,
    StockAdjustmentSerializer,
)
from .vehicles import VehicleSerializer
from .work_orders import (
    CancelWorkOrderSerializer,
    WorkOrderServiceChecklistItemSerializer,
    WorkOrderServiceSerializer,
    StartWorkOrderServiceSerializer,
    CompleteWorkOrderServiceSerializer,
    QualityCheckWorkOrderServiceSerializer,
    WorkOrderPartSerializer,
    WorkOrderPaymentSerializer,
    PaymentReversalSerializer,
    WorkOrderPhotoSerializer,
    WorkOrderEventSerializer,
    WorkOrderMessageSerializer,
    WorkOrderNotificationRuleSerializer,
    InitialWorkOrderServiceItemSerializer,
    WorkOrderSerializer,
    WorkOrderListSerializer,
    WorkOrderDetailSerializer,
    WorkOrderDeliverySignatureSerializer,
    WorkOrderDeliverySignatureCreateSerializer,
    WorkOrderCustomerApprovalSerializer,
    WorkOrderCustomerApprovalCreateSerializer,
    WorkOrderCustomerApprovalDecisionSerializer,
    WorkOrderManualApprovalSerializer,
    WorkOrderCustomerApprovalPublicSerializer,
    ChangeWorkOrderStatusSerializer,
    SendWorkOrderMessageSerializer,
)

__all__ = [
    "WorkshopProfileSerializer",
    "PublicLandingSerializer",
    "WorkshopServiceChecklistTemplateSerializer",
    "ServiceDefaultPartSerializer",
    "GeneralCategorySerializer",
    "PartBrandSerializer",
    "VehicleSerializer",
    "WorkshopServiceSerializer",
    "ServicePackageItemSerializer",
    "ServicePackageSerializer",
    "PartSerializer",
    "PartStockMovementSerializer",
    "StockAdjustmentSerializer",
    "CancelWorkOrderSerializer",
    "WorkOrderServiceChecklistItemSerializer",
    "WorkOrderServiceSerializer",
    "StartWorkOrderServiceSerializer",
    "CompleteWorkOrderServiceSerializer",
    "QualityCheckWorkOrderServiceSerializer",
    "WorkOrderPartSerializer",
    "WorkOrderPaymentSerializer",
    "PaymentReversalSerializer",
    "WorkOrderPhotoSerializer",
    "WorkOrderEventSerializer",
    "WorkOrderMessageSerializer",
    "WorkOrderNotificationRuleSerializer",
    "InitialWorkOrderServiceItemSerializer",
    "WorkOrderSerializer",
    "WorkOrderListSerializer",
    "WorkOrderDetailSerializer",
    "WorkOrderDeliverySignatureSerializer",
    "WorkOrderDeliverySignatureCreateSerializer",
    "WorkOrderCustomerApprovalSerializer",
    "WorkOrderCustomerApprovalCreateSerializer",
    "WorkOrderCustomerApprovalDecisionSerializer",
    "WorkOrderManualApprovalSerializer",
    "WorkOrderCustomerApprovalPublicSerializer",
    "ChangeWorkOrderStatusSerializer",
    "SendWorkOrderMessageSerializer",
]
