# Generated by Django 5.2.14 on 2026-05-07 18:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('workshop', '0005_category_dropdowns_for_parts_and_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('origin', models.CharField(choices=[('work_order', 'Ordem de serviço'), ('manual', 'Manual')], db_index=True, default='work_order', max_length=30)),
                ('description', models.CharField(max_length=220)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('partial', 'Parcial'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], db_index=True, default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_receivable', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='messaging.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_accounts_receivable', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_receivable', to='workshop.workorder')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='ar_status_due_idx'), models.Index(fields=['number'], name='finance_ar_number_idx')],
            },
        ),
    ]
