# Generated by Django 5.2.14 on 2026-05-07 18:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_backfill_delivered_work_order_receivables'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('origin', models.CharField(choices=[('purchase_order', 'Pedido de compra'), ('manual', 'Manual')], db_index=True, default='manual', max_length=30)),
                ('recurrence_type', models.CharField(choices=[('cash', 'À vista'), ('installment', 'Parcelada'), ('fixed_monthly', 'Fixa mensal')], db_index=True, default='cash', max_length=30)),
                ('category', models.CharField(blank=True, help_text='Ex.: aluguel, energia, folha, imposto, fornecedor, manutenção.', max_length=80)),
                ('description', models.CharField(max_length=220)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('partial', 'Parcial'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], db_index=True, default='open', max_length=20)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('installment_total', models.PositiveIntegerField(default=1)),
                ('recurrence_group', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('next_generation_date', models.DateField(blank=True, help_text='Usado em contas fixas mensais para gerar a próxima competência.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_payable', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_payable', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_payable', to='purchasing.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_accounts_payable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountPayablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'PIX'), ('bank_transfer', 'Transferência bancária'), ('debit_card', 'Cartão de débito'), ('credit_card', 'Cartão de crédito'), ('boleto', 'Boleto'), ('other', 'Outro')], default='pix', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('account_payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.accountpayable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payable_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='accountpayable',
            index=models.Index(fields=['status', 'due_date'], name='ap_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='accountpayable',
            index=models.Index(fields=['origin', 'recurrence_type'], name='ap_origin_recur_idx'),
        ),
        migrations.AddIndex(
            model_name='accountpayable',
            index=models.Index(fields=['number'], name='finance_ap_number_idx'),
        ),
        migrations.AddIndex(
            model_name='accountpayable',
            index=models.Index(fields=['recurrence_group'], name='ap_recur_group_idx'),
        ),
        migrations.AddIndex(
            model_name='accountpayablepayment',
            index=models.Index(fields=['paid_at'], name='ap_payment_paid_at_idx'),
        ),
    ]
