# Generated by Django 5.2.14 on 2026-05-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('finance', '0003_accountpayable_accountpayablepayment_and_more'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='counter_sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_receivable', to='attendance.countersale'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='messaging.contact'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='origin',
            field=models.CharField(choices=[('work_order', 'Ordem de serviço'), ('counter_sale', 'Venda avulsa'), ('manual', 'Manual')], db_index=True, default='work_order', max_length=30),
        ),
    ]
