# Generated by Django 5.2.14 on 2026-05-07 20:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_accountreceivable_counter_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('bank_transfer', 'Transferência'), ('mbway', 'MB Way'), ('pix', 'Pix'), ('other', 'Outro')], default='cash', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('account_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to='finance.accountreceivable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts_receivable_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['paid_at'], name='ar_payment_paid_idx')],
            },
        ),
    ]
