# Generated by Django 5.2.14 on 2026-05-10 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def map_legacy_estimate_statuses(apps, schema_editor):
    Estimate = apps.get_model("attendance", "Estimate")
    status_map = {
        "draft": "open",
        "sent": "awaiting_approval",
        "approved": "approved",
        "rejected": "rejected",
        "expired": "expired",
        "converted": "converted",
        "cancelled": "cancelled",
    }
    for old_status, new_status in status_map.items():
        Estimate.objects.filter(status=old_status).update(status=new_status)


def reverse_legacy_estimate_statuses(apps, schema_editor):
    # A migracao de volta nao consegue reconstruir com seguranca se "open" era draft ou outro estado novo.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('workshop', '0023_workorder_source_estimate_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatepartitem',
            name='approved_by_customer',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='estimatepartitem',
            name='customer_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimatepartitem',
            name='service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='attendance.estimateserviceitem'),
        ),
        migrations.AddField(
            model_name='estimateserviceitem',
            name='approved_by_customer',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='estimateserviceitem',
            name='customer_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(map_legacy_estimate_statuses, reverse_legacy_estimate_statuses),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('diagnosis', 'Em diagnostico'), ('awaiting_approval', 'Aguardando aprovacao'), ('approved', 'Aprovado'), ('partially_approved', 'Aprovado parcialmente'), ('rejected', 'Rejeitado'), ('expired', 'Expirado'), ('converted', 'Convertido em OS'), ('cancelled', 'Cancelado')], db_index=True, default='open', max_length=30),
        ),
        migrations.CreateModel(
            name='EstimateCustomerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('partially_approved', 'Aprovado parcialmente'), ('rejected', 'Rejeitado'), ('expired', 'Expirado')], db_index=True, default='pending', max_length=30)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('customer_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=30)),
                ('decision_name', models.CharField(blank=True, max_length=180)),
                ('decision_document', models.CharField(blank=True, max_length=30)),
                ('decision_notes', models.TextField(blank=True)),
                ('decision_selected_services', models.JSONField(blank=True, default=list)),
                ('decision_selected_parts', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('decision_user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_approvals', to='attendance.estimate')),
                ('generated_work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_estimate_approval', to='workshop.workorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_estimate_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aprovação digital de orçamento',
                'verbose_name_plural': 'aprovações digitais de orçamento',
                'ordering': ['-requested_at', '-id'],
                'indexes': [models.Index(fields=['estimate', 'status'], name='est_approval_status_idx'), models.Index(fields=['token', 'status'], name='est_approval_token_idx')],
            },
        ),
    ]
