# Generated by Django 5.2.14 on 2026-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_estimatepartitem_approved_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='tank_level_percent',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], default=0),
        ),
    ]
