# Generated by Django 5.2.14 on 2026-05-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_estimate_tank_level_percent'),
        ('workshop', '0025_vehicle_door_count_vehicle_has_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateserviceitem',
            name='source_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_service_lines', to='workshop.servicepackage'),
        ),
    ]
