# Generated by MotorMind maintenance task.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0030_service_default_parts"),
        ("attendance", "0004_estimateserviceitem_source_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="revision_work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revision_estimates",
                to="workshop.workorder",
            ),
        ),
    ]
