# Generated by Django 5.2.14 on 2026-05-14 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_normalize_estimate_statuses(apps, schema_editor):
    Estimate = apps.get_model("attendance", "Estimate")
    mapping = {
        "open": "draft",
        "diagnosis": "draft",
        "awaiting_approval": "sent",
        "partially_approved": "approved",
    }
    for old, new in mapping.items():
        Estimate.objects.filter(status=old).update(status=new)


def backwards_restore_estimate_statuses(apps, schema_editor):
    Estimate = apps.get_model("attendance", "Estimate")
    Estimate.objects.filter(status="draft").update(status="open")
    Estimate.objects.filter(status="sent").update(status="awaiting_approval")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_estimate_cancellation_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='approval_method',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='estimate',
            name='approved_by',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='estimate',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(forwards_normalize_estimate_statuses, backwards_restore_estimate_statuses),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('converted', 'Convertido em OS')], db_index=True, default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='EstimateStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_status_history', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='attendance.estimate')),
            ],
            options={
                'verbose_name': 'histórico de status do orçamento',
                'verbose_name_plural': 'histórico de status dos orçamentos',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['estimate', 'new_status'], name='est_hist_status_idx')],
            },
        ),
    ]
