import React, { useEffect, useState } from "react";
import { Card, Col, Row, Table } from "react-bootstrap";
import { Link } from "react-router-dom";
import api,{apiError} from "../api/client";
import ErrorAlert from "../components/ErrorAlert";
import PageHeader from "../components/PageHeader";
import StatusBadge from "../components/StatusBadge";
import { money } from "../workshopOptions";
export default function WorkshopDashboardPage(){const [data,setData]=useState(null);const [error,setError]=useState("");async function load(){try{setData((await api.get("/workshop/dashboard/")).data)}catch(e){setError(apiError(e))}}useEffect(()=>{load()},[]);const c=data?.counts||{};const cards=[["OS abertas",c.open_work_orders],["Aguardando aprovação",c.awaiting_approval],["Em execução",c.in_progress],["Prontas",c.ready],["Veículos",c.vehicles],["Peças baixo estoque",c.low_stock_parts],["Recebido no mês",money(c.paid_month)]];return <><PageHeader title="Dashboard oficina" subtitle="Resumo de ordens de serviço, estoque e financeiro."/><ErrorAlert error={error} onClose={()=>setError("")}/><Row className="g-3 mb-4">{cards.map(([l,v])=><Col md={3} xl key={l}><Card className="card-kpi h-100"><Card.Body><div className="text-muted small">{l}</div><div className="display-6 fw-bold">{v||0}</div></Card.Body></Card></Col>)}</Row><Row className="g-3"><Col lg={8}><Card className="border-0 shadow-sm"><Card.Header className="bg-white fw-semibold">Ordens recentes</Card.Header><Card.Body className="p-0"><Table responsive hover className="mb-0"><thead><tr><th>Número</th><th>Cliente</th><th>Veículo</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>{(data?.recent_work_orders||[]).map(o=><tr key={o.id}><td className="fw-semibold">{o.number}</td><td>{o.customer_name}</td><td>{o.vehicle_display||"-"}</td><td><StatusBadge value={o.status} label={o.status_label}/></td><td>{money(o.grand_total)}</td><td><Link to={`/work-orders/${o.id}`}>Abrir</Link></td></tr>)}</tbody></Table></Card.Body></Card></Col><Col lg={4}><Card className="border-0 shadow-sm"><Card.Header className="bg-white fw-semibold">Baixo estoque</Card.Header><Card.Body className="p-0"><Table responsive hover className="mb-0"><tbody>{(data?.low_stock_parts||[]).map(p=><tr key={p.id}><td>{p.sku}</td><td>{p.name}</td><td>{p.stock_quantity} {p.unit}</td></tr>)}</tbody></Table></Card.Body></Card></Col></Row></>}
