# Generated by Django 5.2.14 on 2026-05-10 07:27

import accounts.fields
from django.db import migrations


def encrypt_existing_whatsapp_tokens(apps, schema_editor):
    ChannelConfiguration = apps.get_model('messaging', 'ChannelConfiguration')
    for config in ChannelConfiguration.objects.exclude(whatsapp_access_token=''):
        config.whatsapp_access_token = config.whatsapp_access_token
        config.save(update_fields=['whatsapp_access_token'])


def decrypt_existing_whatsapp_tokens(apps, schema_editor):  # noqa: ARG001
    from accounts.encryption import decrypt_credential

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, whatsapp_access_token FROM messaging_channelconfiguration WHERE whatsapp_access_token <> ''")
        rows = cursor.fetchall()
        for pk, raw_token in rows:
            cursor.execute(
                "UPDATE messaging_channelconfiguration SET whatsapp_access_token = %s WHERE id = %s",
                [decrypt_credential(raw_token), pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_whatsapp_dummy_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfiguration',
            name='whatsapp_access_token',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(encrypt_existing_whatsapp_tokens, decrypt_existing_whatsapp_tokens),
    ]
